export const ACTIONTYPE = {
    SET_USERS: "SET_USERS",
    ADD_TO_CART:"ADD_TO_CART",
    TOGGLE_CART:'TOGGLE_CART',
    ADD_PRODUCT:'ADD_PRODUCT',
    REMOVE_PRODUCT:"REMOVE_PRODUCT",
    INCREMENT_PRODUCT:"INCREMENT_PRODUCT",
    DECREMENT_PRODUCT:'DECREMENT_PRODUCT',  
    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
}